package com.teramint.cayenne.entity.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _LevelInfo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _LevelInfo extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String ID_PROPERTY = "id";
    @Deprecated
    public static final String LEVEL_NAME_PROPERTY = "levelName";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Integer> ID = new Property<Integer>("id");
    public static final Property<String> LEVEL_NAME = new Property<String>("levelName");

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setLevelName(String levelName) {
        writeProperty("levelName", levelName);
    }
    public String getLevelName() {
        return (String)readProperty("levelName");
    }

}
